---
galaxy_info:
  author: your_name
  description: Setup Kubernetes on Ubuntu
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - kubernetes
    - k8s
    - container
dependencies: []
collections:
  - kubernetes.core
