all:
  children:
    master:
      hosts:
        master-node:
          ansible_host: 192.168.1.100  # Replace with your master IP
          node_type: master
    workers:
      hosts:
        worker-node-1:
          ansible_host: 192.168.1.101  # Replace with your worker IP
          node_type: worker
        worker-node-2:
          ansible_host: 192.168.1.102  # Replace with your worker IP
          node_type: worker
